version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: slackbot-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slackbot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: ../deploy/Dockerfile.backend
    container_name: slackbot-backend
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: slackbot
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ../deploy/Dockerfile.frontend
    container_name: slackbot-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  db_data:
